# Generated by Django 2.1.9 on 2019-06-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
