# Generated by Django 2.1.9 on 2019-06-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(default='Ary', max_length=100),
            preserve_default=False,
        ),
    ]
