# Generated by Django 2.1.9 on 2019-06-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190604_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default='Сокращённый саммери чтобы посмотреть как посты отображаться будут'),
        ),
    ]
