# Generated by Django 2.1.9 on 2019-06-25 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_postviewcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='viewcount',
        ),
    ]
