# Generated by Django 2.1.9 on 2019-06-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_remove_post_viewcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='jvachka',
            field=models.TextField(default='Text'),
            preserve_default=False,
        ),
    ]
