# Generated by Django 2.1.9 on 2019-07-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_postview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='human.png', upload_to=''),
            preserve_default=False,
        ),
    ]
