# Generated by Django 2.1.9 on 2019-07-05 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_comment_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profile',
        ),
    ]
