# Generated by Django 2.1.10 on 2019-07-05 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_auto_20190705_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='main',
            new_name='slide',
        ),
    ]
