# Generated by Django 2.1.9 on 2019-07-26 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
    ]
