# Generated by Django 2.1.10 on 2019-07-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_auto_20190718_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
    ]
